baseURL = "https://business.engmarta.com/"
languageCode = "en-us"
title = "Business English with Marta"
theme = "hugo-theme-stack"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
avatar = "/img/avatar.png"

[params]
  favicon = "images/favicon.png"
  customCSS = ["css/main.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[languages.en]
    languageName = "English"
    weight = 1

  [languages.zh-cn]
    languageName = "中文"
    weight = 2

  [languages.uk]
    languageName = "Українська"
    weight = 3

  [languages.ru]
    languageName = "Русский"
    weight = 4

  [languages.es]
    languageName = "Español"
    weight = 5

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100
[menu.main.params]
icon = "home"

[[menu.main]]
name = "Lessons"
url = "/post/lessons/"
weight = -70
[menu.main.params]
icon = "book"

[[menu.main]]
name = "Pricing"
url = "/post/pricing/"
weight = -69
[menu.main.params]
icon = "credit-card"

[[menu.main]]
name = "Contact"
url = "/post/contact/"
weight = -60
[menu.main.params]
icon = "book"

[[menu.main]]
name = "Resources"
url = "/page/resources/"
weight = -20
[menu.main.params]
icon = "links"